### ISSUE TITLE
Couldn't load icon icons/icon16.png specified in icons.

### ISSUE THREAD

**Issue by muygalan** [getoslash/oslash#17]
Hi OSlash Team,

I'm trying to import the open source OSlash folder into Microsoft Edge. I'm following the instructions as [indicated on your blog](https://www.oslash.com/blog/sunsetting-oslash).

After clicking **Load Unpacked**, and selecting the `oslash-main` folder, I receive the following error message: "_Couldn't load icon icons/icon16.png specified in icons._"

Here is a [1 minute video recording](https://record.joshuagalan.com/recordings/M1LjMWjJ7A9dEvkFHfAC?onlyRecording=1) of the problem. Please advise.

**Comment by tanmay-d-shah** [comment]
Hey @muygalan. Apologies for the inconvenience. Can you please download the zip file from our releases page.
Here is the link which will automatically initiate download of the [zip file](https://github.com/getoslash/oslash/releases/download/%40v1.1.0/oslash-chrome-extension.zip)

Here is the link to our [releases page](https://github.com/getoslash/oslash/releases)
All new future releases would be posted here. You can download them from this page.

Let me know if you face any further issues
Regards,
Tanmay

**Comment by muygalan** [comment]
@tanmay-d-shah That worked. Thanks for the follow-up!

Now that it's functioning correctly, I'd **really** love to see the original keyboard [shortcut command](https://github.com/getoslash/oslash/issues/15) implemented. 

(I used to use `CTRL + J` personally) This is an essential feature to have.
