### ISSUE TITLE
Fails To Install on Mac | Resolved

### ISSUE THREAD

**Issue by TribalHouse** [getoslash/oslash#9]
Error Details:

Failed to load extension
File
~/Downloads/oslash-main
Error
Could not load icon 'icons/icon16.png' specified in 'action'.
Could not load manifest.

**Comment by murlx** [comment]
Same issue on Windows also, Tried to reachout to them through email, But emailID doesn't exist 🥲

**Comment by TribalHouse** [comment]
Here is the fix:

1. Open the downloaded OSlash folder.
2. Find and move the icons folder out of the Public directory (if it's inside it) to the main directory, where manifest.json is.
3. Your main directory should now include:
4. An icons folder with icon16.png, icon32.png, icon48.png, icon128.png.
5. The manifest.json file.
6. Head to chrome://extensions/ in Chrome, turn on "Developer mode", and hit "Load unpacked".
7. Select the updated main OSlash folder

**Comment by BREEDER-CARE** [comment]
Thanks, TribalHouse, for the moving icon folder advised. 
I can' load the unpacked now but seem like it isn't work when i click on the extension icon just nothing shown?
I already disable the original extension already... Any ideas to make it works?

**Comment by PPKPK** [comment]
How to fix the extension is unable to work at all :(
"Service worker registration failed. Status code: 11"

![Screen Shot 2566-11-13 at 19 06 07](https://github.com/getoslash/oslash/assets/30545688/f3215771-606f-4b3b-81c3-6a6f14e9051b)

**Comment by TribalHouse** [comment]
> How to fix the extension is unable to work at all :( "Service worker registration failed. Status code: 11"
> 
> ![Screen Shot 2566-11-13 at 19 06 07](https://user-images.githubusercontent.com/30545688/282455954-f3215771-606f-4b3b-81c3-6a6f14e9051b.png)

To Fix this issue, you need to convert the files from TypeScript into JS as Chrome does not recognize TS.

I was able to recompile them into JS but I am still getting an error from the files.

I see @tanmay-d-shah has been assigned the task, hopefully we get a fix soon :)

**Comment by PPKPK** [comment]
> > How to fix the extension is unable to work at all :( "Service worker registration failed. Status code: 11"
> > ![Screen Shot 2566-11-13 at 19 06 07](https://user-images.githubusercontent.com/30545688/282455954-f3215771-606f-4b3b-81c3-6a6f14e9051b.png)
> 
> To Fix this issue, you need to convert the files from TypeScript into JS as Chrome does not recognize TS.
> 
> I was able to recompile them into JS but I am still getting an error from the files.
> 
> I see @tanmay-d-shah has been assigned the task, hopefully we get a fix soon :)

So is the GitHub project is really usable right now? Just bit complicate to set it up here.

**Comment by tanmay-d-shah** [comment]
Hi guys. I request you all to please download the zipped extension from releases for usage. Here is a video on how to do that:
https://drive.google.com/file/d/1nPZqKjsDWJezidBEAS1R8fDgsb3AYWgg/view?usp=sharing

**Comment by naveenann** [comment]
@PPKPK from the screenshot i can see that you are trying to load a `.ts` file, Can you try download the latest release from this link https://github.com/getoslash/oslash/releases/download/%40v1.1.0/oslash-chrome-extension.zip, 
Let us know if you still

**Comment by TribalHouse** [comment]
> Hi guys. I request you all to please download the zipped extension from releases for usage. Here is a video on how to do that: https://drive.google.com/file/d/1nPZqKjsDWJezidBEAS1R8fDgsb3AYWgg/view?usp=sharing
> 
> Let me know if the issue still persists. Thanks

Thanks @tanmay-d-shah  Its working now.
